services:
  - type: web
    name: cefr-master
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATA_DIR
        value: /var/data
      - key: UPLOADS_DIR
        value: /var/data/uploads
    disk:
      name: cefr-master-data
      mountPath: /var/data
      sizeGB: 1